server:
  origin: 'localhost:3001'
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
  credentials: true
  allowedHeaders: 'Origin,X-Requested-With,Content-Type,Accept,Authorization'

db:
  host: 'localhost'
  username: 'root'
  password: 'kiet1212001'
  synchronize: true

jwt:
  secret: 'topSecret51'
