server:
  origin: 'http://khamma-nestjs-task-management-frontend.s3-website-ap-southeast-2.amazonaws.com'
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
  credentials: true
  allowedHeaders: 'Origin,X-Requested-With,Content-Type,Accept,Authorization'
db:
  synchronize: false
